-- 코드를 입력하세요
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) AS count
  FROM ANIMAL_INS 
 WHERE 1=1
   AND (ANIMAL_TYPE LIKE 'Dog%') OR (ANIMAL_TYPE LIKE 'Cat%') 

 GROUP BY ANIMAL_TYPE
 ORDER BY ANIMAL_TYPE
 ;