SELECT U.USER_ID
     , U.NICKNAME
     , U.CITY||' '|| U.STREET_ADDRESS1||' '|| U.STREET_ADDRESS2 AS 전체주소
     , SUBSTR(U.TLNO,'1','3') || '-' || SUBSTR(U.TLNO,'4','4') || '-' || SUBSTR(U.TLNO,'8','4') AS 전화번호
  FROM USED_GOODS_USER U
     ,(SELECT COUNT(B1.BOARD_ID) AS CNT
            , B1.WRITER_ID
         FROM USED_GOODS_BOARD B1
        WHERE 1=1
        GROUP BY B1.WRITER_ID HAVING COUNT(B1.BOARD_ID) >= 3
      ) B
 WHERE 1=1
   AND B.WRITER_ID = U.USER_ID
 ORDER BY U.USER_ID DESC