-- 코드를 입력하세요
SELECT C.HISTORY_ID
     , C.CAR_ID
     , TO_CHAR(C.START_DATE,'YYYY-MM-DD') as START_DATE
     , TO_CHAR(C.END_DATE,'YYYY-MM-DD') as END_DATE
     , CASE WHEN (C.END_DATE - C.START_DATE) +1 >= 30
            THEN '장기 대여'
            ELSE '단기 대여'
       END as RENT_TYPE
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
 WHERE 1=1
   AND TO_CHAR(C.START_DATE,'YYYYMM') = '202209'
   
 ORDER BY C.HISTORY_ID DESC