-- 코드를 입력하세요
SELECT p1.PRODUCT_CODE
     , SUM(p1.PRICE * o1.SALES_AMOUNT) as SALES
  FROM PRODUCT p1
     , OFFLINE_SALE o1
 WHERE 1=1
   AND p1.PRODUCT_ID = o1.PRODUCT_ID
 GROUP BY p1.PRODUCT_CODE
 ORDER BY SALES DESC, p1.PRODUCT_CODE ASC