-- 코드를 입력하세요
SELECT U.USER_ID AS USER_ID
     , U.NICKNAME AS NICENAME
     , B.TOTAL_SALES
  FROM USED_GOODS_USER U
     , (SELECT SUM(B.PRICE) AS TOTAL_SALES
             , B.WRITER_ID
          FROM USED_GOODS_BOARD B
         WHERE 1=1
          AND B.STATUS = 'DONE'
         GROUP BY B.WRITER_ID
        ) B
  WHERE 1=1
    AND B.WRITER_ID = U.USER_ID
    AND TOTAL_SALES >= 700000
  ORDER BY TOTAL_SALES 
    
