-- 코드를 입력하세요
SELECT f1.WAREHOUSE_ID
     , f1.WAREHOUSE_NAME
     , f1.ADDRESS
     , NVL(f1.FREEZER_YN,'N')
  FROM FOOD_WAREHOUSE f1
 WHERE 1=1
  AND INSTR(f1.ADDRESS, '경기') > 0
 ORDER BY f1.WAREHOUSE_ID
 ;