-- 코드를 입력하세요
SELECT DISTINCT(C.CAR_ID)
  FROM CAR_RENTAL_COMPANY_CAR C 
     , CAR_RENTAL_COMPANY_RENTAL_HISTORY H
 WHERE 1=1 
   AND H.CAR_ID = C.CAR_ID 
   AND C.CAR_TYPE = '세단'
   AND TO_CHAR(H.START_DATE,'YYYYMMDD') BETWEEN '20221001' AND '20221031'
 ORDER BY C.CAR_ID DESC 