-- 코드를 입력하세요
SELECT I1.INGREDIENT_TYPE
     , SUM(F1.TOTAL_ORDER) AS TOTAL_ORDER
  FROM FIRST_HALF F1
     , ICECREAM_INFO I1
 WHERE 1=1 
   AND I1.FLAVOR = F1.FLAVOR
 GROUP BY I1.INGREDIENT_TYPE
 ORDER BY TOTAL_ORDER 
   

   