-- 코드를 입력하세요
SELECT B1.BOOK_ID, A1.AUTHOR_NAME, TO_CHAR(B1.PUBLISHED_DATE, 'yyyy-mm-dd') AS PUBLISHED_DATE
  FROM BOOK B1 , AUTHOR A1
 WHERE 1=1
  AND B1.AUTHOR_ID = A1.AUTHOR_ID
  AND B1.CATEGORY IN('경제')
  ORDER BY B1.PUBLISHED_DATE
  ;