-- 코드를 입력하세요
SELECT U.BOARD_ID AS BOARD_ID
     , U.WRITER_ID AS WRITER_D
     , U.TITLE AS TITLE
     , U.PRICE AS PRICE
     , DECODE(U.STATUS,'SALE','판매중','DONE','거래완료','RESERVED','예약중') AS STATUS
  FROM USED_GOODS_BOARD U
 WHERE 1=1
   AND TO_CHAR(U.CREATED_DATE, 'YYYYMMDD') = '20221005'
   
  ORDER BY U.BOARD_ID DESC