-- 코드를 입력하세요
SELECT B1.CATEGORY AS CATEGORY
     , SUM(B2.SALES) AS TOTAL_SALES
  FROM BOOK B1
     , BOOK_SALES B2
 WHERE 1=1
   AND B1.BOOK_ID = B2.BOOK_ID
   AND TO_CHAR(B2.SALES_DATE,'YYYYMM') = '202201'
 GROUP BY B1.CATEGORY
 ORDER BY B1.CATEGORY