-- 코드를 입력하세요
SELECT P.PRICE_GROUP
     , COUNT(1) AS PRODUCTS
  FROM (SELECT FLOOR(IP.PRICE/10000) * 10000 AS PRICE_GROUP
         FROM PRODUCT IP
       )P
 WHERE 1=1
  GROUP BY P.PRICE_GROUP
  ORDER BY P.PRICE_GROUP