SELECT MCDP_CD AS "진료과 코드"
     , COUNT(1) AS "5월예약건수"
  FROM APPOINTMENT
 WHERE 1=1
  AND TO_CHAR(APNT_YMD, 'YYYYMMDD') BETWEEN '202205' AND '202206'
  GROUP BY MCDP_CD
  ORDER BY COUNT(1), MCDP_CD
  ;